[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "3.4.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.5.3"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "=0.24.2"

# Overrides needed to get Cosmos SDK to be fetched correctly :-(
[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.9.2"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.23.1-rc0"

[[constraint]]
  name = "github.com/alexanderbez/godash"
  version = "0.0.3"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.21.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
